AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Company - {{ cookiecutter.companyNameTitle }}
  Project - {{ cookiecutter.projectNameTitle }} 
  Lambda - {{cookiecutter.lambdaName}}
  Description - {{cookiecutter.lambdaDescription}}

Globals:
  Function:
    Timeout: 30    
    MemorySize: 128
    Runtime: nodejs12.x

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/awsHandler.handler
      Events:
        Service:
          Type: Api
          Properties:
            Path: /
            Method: get
        Service:
          Type: Api
          Properties:
            Path: /
            Method: post
            

Outputs:
  ServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for service function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"